name: Testnet Deployment

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.18.0 ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm install
    - name: Production build
      run: npm run build
      env:
        VITE_APP_CLIENT_PASSPHRASE: ${{ secrets.WALLET_TESTNET_CLIENT_PASSPHRASE }}
        VITE_APP_CLIENT_PUBLIC_KEY: ${{ secrets.WALLET_TESTNET_CLIENT_PUBLIC_KEY }}
        VITE_APP_CLIENT_PRIVATE_KEY: ${{ secrets.WALLET_TESTNET_CLIENT_PRIVATE_KEY }}
        VITE_APP_WALLET_APP_PUBLIC_KEY: ${{ secrets.WALLET_TESTNET_APP_PUBLIC_KEY }}
        VITE_APP_WALLET_APP_AAT_SIGNATURE: ${{ secrets.WALLET_TESTNET_APP_AAT_SIGNATURE }}
        VITE_APP_POKT_USD_VALUE: ${{ secrets.POKT_USD_MARKET_PRICE }}
        VITE_APP_SECURE_LS_ENCRYPTION_SECRET: ${{ secrets.SECURE_LS_ENCRYPTION_SECRET }}
        VITE_APP_SECURE_LS_ENCODING_TYPE: "aes"
        VITE_APP_SECURE_LS_IS_COMPRESSION: true
        VITE_APP_DISPATCHERS: "https://node1.testnet.pokt.network,https://node2.testnet.pokt.network,https://node3.testnet.pokt.network,https://node4.testnet.pokt.network,https://node5.testnet.pokt.network"
        VITE_APP_HTTP_PROVIDER: "https://node1.testnet.pokt.network:443"
        VITE_APP_MAX_DISPATCHERS: 0
        VITE_APP_PROVIDER_TYPE: "http"
        VITE_APP_AAT_VERSION: "0.0.1"
        VITE_APP_BLOCK_EXPLORER_BASE_URL: "https://explorer.testnet.pokt.network"
        VITE_APP_DASHBOARD_BASE_URL: "https://dashboard.testnet.pokt.network"
        VITE_APP_BUY_POKT_BASE_URL: "https://forum.pokt.network/t/secondary-markets-for-pokt/629"
        VITE_APP_CHAIN: "0002"
        VITE_APP_CHAIN_ID: "testnet"
        VITE_APP_BLOCK_TIME: "900000"
        VITE_APP_MAX_TRANSACTION_LIST_COUNT: "5000"
        VITE_APP_MIN_TRANSACTION_LIST_COUNT: "200"
        VITE_APP_TX_FEE: "10000"
        VITE_APP_SESSION_LENGTH: "15"
        VITE_APP_GATEWAY_BASE_URL: "https://testnet.gateway-testnet.pokt.network/v1/lb/6214f2f34827d34f48d35f6a"
        VITE_APP_HTTP_TIMEOUT: 0
        VITE_APP_USE_LEGACY_CODEC: "false"
        VITE_APP_HTTP_HEADERS: '{"Content-Type": "application/json"}'
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_TESTNET_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
    - name: Clear CloudFront Cache
      uses: awact/cloudfront-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION_ID: ${{ secrets.AWS_TESTNET_DISTRIBUTION_ID }}
    - name: Deploy to GCS
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: portal-gb-prod
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      with:
        args: -m rsync -r ./build gs://pocket-wallet-testnet-frontend
        cli: gsutil
    - name: Clear Cloud CDN Cache
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: portal-gb-prod
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      with:
        args: compute url-maps invalidate-cdn-cache wallet-testnet-url-map --path \"/*\"
